<a href="https://colab.research.google.com/github/vpbajaj/Personal-Projects/blob/master/Personality_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

Kaggle problem

In [ ]:
train = pd.read_csv('/content/drive/My Drive/mbti_1.csv')

In [ ]:
train.head()

type                                              posts
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   https://www.youtube.com/wat...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [ ]:
label = []
texts = []
repeat = []
for x in train['type']:
    label.append(x)
    if x not in repeat:
        repeat.append(x)

In [ ]:
l = { repeat[i] : i for i in range(0, len(repeat) ) }
l

{'ENFJ': 5,
 'ENFP': 7,
 'ENTJ': 4,
 'ENTP': 1,
 'ESFJ': 15,
 'ESFP': 13,
 'ESTJ': 14,
 'ESTP': 12,
 'INFJ': 0,
 'INFP': 6,
 'INTJ': 3,
 'INTP': 2,
 'ISFJ': 10,
 'ISFP': 8,
 'ISTJ': 11,
 'ISTP': 9}

In [ ]:
labels = []
for x in label:
    index = l.get(x)
    labels.append(index)
for x in train['posts']:
    texts.append(x)

In [ ]:
from keras.preprocessing.text import Tokenizer 
from keras.preprocessing.sequence import pad_sequences

maxlen = 4000
training_samples = 500
validation_samples = 1000
max_words = 10000

tokenizer = Tokenizer(num_words=max_words) 
tokenizer.fit_on_texts(texts) 
sequences = tokenizer.texts_to_sequences(texts)

word_index = tokenizer.word_index 
print('Found %s unique tokens.' % len(word_index))

data = pad_sequences(sequences, maxlen=maxlen)



labels = np.asarray(labels) 
print('Shape of data tensor:', data.shape) 
print('Shape of label tensor:', labels.shape)

indices = np.arange(data.shape[0]) 
np.random.shuffle(indices) 
data = data[indices] 
labels = labels[indices]

x_train = data[:] 
y_train = labels[:] 
x_val = data[training_samples: training_samples + validation_samples] 
y_val = labels[training_samples: training_samples + validation_samples]

Found 160094 unique tokens.
Shape of data tensor: (8675, 4000)
Shape of label tensor: (8675,)


In [ ]:
x_train.shape

(8675, 4000)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
forest.fit(x_train, y_train)
forest.score(x_train, y_train)

0.9920461095100864

In [ ]:
pred = forest.predict(x_val)
print(pred)


[ 8  3  2  6  3  7  0  2  3  2  6  2  2  1  2  2  8  6 11  0  6  7  3  6
  2  3  6  6  6  3  7  0  6  1  0  2  6  0  9  5  4  2  4  8 15  2  0 11
  6  6  4  2  6  6  2  6 11  3  9  1  3  6  4  0  7  3  6 10  2  0  3  0
  2  9  3  2  6  2  2  3  0  0  2  3  0  2  2  0  2  4  6  2  2 11  1  0
  8  2  0  2  7  0  1  3  6  6  6  2  0  1  0  1  3  6  6  3  9  3  5 12
  3  3  1  1  6  1  6 13  4  6  2  6  0  7  0  3  3  6  2  6  6  5  6  3
  3  0 10  3  0  8  3  7  1  1  6  2  0  6  2  7  2  5  3  0  1  7  2 11
  2  6  0  6  2  0  7  1  0  6  2  0  3  4  2  2  2  0  1  2  1  0  6  8
  6  2  1  2  9  2  4  1  6  2  3  4  7  2  2  2  1  5  2  8  2  6  6  6
  6  9  7  6  7  0  6  1  1  2  7  6  6  0  0  2  3  2  6  4  7  1  7  2
 10  4  6  7  1  9  3  9  0  7  3  6  7  2  7  6  2  9  3  1  0  2  0  3
  6  6  6  8  9  4  6  6  6  6  2  6  0  0  0  3  2 11  7  6  6  6  0  8
  7  2  3  2  0  4  3  6  6  7  0  2  0  2  9  2  6  6  0  0  8  3  7  6
  0  6  6  2  6  3  6  2  0 10  0  7  3  6  2  2  0

In [ ]:

print(y_val)

[ 8  3  2  6  3  7  0  2  3  2  6  2  2  1  2  2  8  6 11  0  6  7  3  6
  2  3  6  6  6  3  7  0  6  1  0  2  6  0  9  5  4  2  4  8 15  2  0 11
  6  6  4  2  6  6  2  6 11  3  9  1  3  6  4  0  7  3  6 10  2  0  3  0
  2  9  3  2  6  2  2  3  0  0  2  3  0  2  2  0  2  4  6  2  2 11  1  0
  8  2  0  2  7  0  1  3  6  6  6  2  0  1  0  1  3  6  6  3  9  3  5 12
  3  3  1  1  6  1  6 13  4  6  2  6  0  7  0  3  3  6  2  6  6  5  6  3
  3  0 10  3  0  8  3  7  1  1  6  2  0  6  2  7  2  5  3  0  1  7  2 11
  2  6  0  6  2  0  7  1  0  6  2  0  3  4  2  2  2  0  1  2  1  0  6  8
  6  2  1 12  9  2  4  1  6  2  3  4  7  2  2  2  1  5  2  8  2  6  6  6
  6  9  7  6  7  0  6  1  1  2  7  6  6  0  0  2  3  2  6  4  7  1  7  2
 10  4  6  7  1  9  3  9  0  7  3  6  7  2  7  6  2  9  3  1  0  2  0  3
  6 14  6  8  9  4  6  6  6  6  2  6  0  0  0  3  2 11  7  6  6  6  0  8
  7  2  3  2  0  4  3  6  6  7  0  2  0  2  9  2  6  6  0  0  8  3  7  6
  0  6  6  2  6  3  6  2  0 10  0  7  3  6  2  2  0

In [ ]:
from sklearn.metrics import confusion_matrix 

cm = confusion_matrix(y_val, forest.predict(x_val)) 
#extracting TN, FP, FN, TP
confusion_matrix(y_val, forest.predict(x_val)).ravel()
num=0
den=0
for i in range(0, len(cm)):
  num += cm[i][i]
  for j in range(0, len(cm[i])):
    den += cm[i][j]
print(cm)
print (num/den)
print()# Print a new line

[[164   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  74   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 164   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   1 131   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  30   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  17   0   0   0   0   0   0   0   0   0   0]
 [  1   0   0   0   0   0 219   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   1  85   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0  23   0   0   0   0   0   0   0]
 [  1   0   0   1   0   0   0   0   0  32   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0  18   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  18   0   0   0   0]
 [  0   0   1   0   0   0   0   0   0   0   0   0  10   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0]
 [  0   0   0   0   0   0   1   0   0   0   0   0   0   0   3 